# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("东南大学SARA射电望远镜")
        MainWindow.resize(800, 600)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(150, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setBaseSize(QtCore.QSize(-12144, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK SC Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(228, 228, 228);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        
        # 创建按钮组
        self.button_group = QtWidgets.QButtonGroup(MainWindow)
        self.button_group.setExclusive(True)  # 设置互斥
        button_style = """
        QPushButton{
              border-top: 3px outset transparent;
              border-bottom: 7px outset transparent;
              border-right: 3px outset transparent;
              border-left:20px outset transparent;
                text-align: left;   /* 文本左对齐 */

              icon-size: 20px;

              background-color: rgb(228, 228, 228);
        }


        /* 鼠标悬停 */
        QPushButton:hover{
              background-color: rgb(205, 205, 205);
        }

        /* 点击和按下 */
        QPushButton:pressed,QPushButton:checked{
              background-color: rgb(205, 205, 205);
        }

        QPushButton:default {
          border-color: navy; /* make the default button prominent */
        }
"""
        
        self.btn_spectrum = QtWidgets.QPushButton(self.frame)
        self.btn_spectrum.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK SC")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_spectrum.setFont(font)
        self.btn_spectrum.setStyleSheet(button_style)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/icon_signal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_spectrum.setIcon(icon)
        self.btn_spectrum.setCheckable(True)
        self.btn_spectrum.setChecked(True)  # 默认选中第一个
        self.btn_spectrum.setObjectName("btn_spectrum")
        self.verticalLayout.addWidget(self.btn_spectrum)
        self.button_group.addButton(self.btn_spectrum, 0)  # 添加到按钮组，ID为0
        
        self.btn_record = QtWidgets.QPushButton(self.frame)
        self.btn_record.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK SC")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_record.setFont(font)
        self.btn_record.setStyleSheet(button_style)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/icon_save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_record.setIcon(icon1)
        self.btn_record.setCheckable(True)
        self.btn_record.setChecked(False)
        self.btn_record.setObjectName("btn_record")
        self.verticalLayout.addWidget(self.btn_record)
        self.button_group.addButton(self.btn_record, 1)  # 添加到按钮组，ID为1
        
        self.btn_direction = QtWidgets.QPushButton(self.frame)
        self.btn_direction.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK SC")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_direction.setFont(font)
        self.btn_direction.setStyleSheet(button_style)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/icon_radar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_direction.setIcon(icon2)
        self.btn_direction.setCheckable(True)
        self.btn_direction.setChecked(False)
        self.btn_direction.setObjectName("btn_direction")
        self.verticalLayout.addWidget(self.btn_direction)
        self.button_group.addButton(self.btn_direction, 2)  # 添加到按钮组，ID为2
        
        self.btn_calibration = QtWidgets.QPushButton(self.frame)
        self.btn_calibration.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK SC")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_calibration.setFont(font)
        self.btn_calibration.setStyleSheet(button_style)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/icon_cali.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_calibration.setIcon(icon3)
        self.btn_calibration.setCheckable(True)
        self.btn_calibration.setChecked(False)
        self.btn_calibration.setObjectName("btn_calibration")
        self.verticalLayout.addWidget(self.btn_calibration)
        self.button_group.addButton(self.btn_calibration, 3)  # 添加到按钮组，ID为3
        
        self.btn_about = QtWidgets.QPushButton(self.frame)
        self.btn_about.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK SC")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_about.setFont(font)
        self.btn_about.setStyleSheet(button_style)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/icon_info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_about.setIcon(icon4)
        self.btn_about.setCheckable(True)
        self.btn_about.setChecked(False)
        self.btn_about.setObjectName("btn_about")
        self.verticalLayout.addWidget(self.btn_about)
        self.button_group.addButton(self.btn_about, 4)  # 添加到按钮组，ID为4
        
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.logo_seu = QtWidgets.QLabel(self.frame)
        self.logo_seu.setPixmap(QtGui.QPixmap(":/icon/icon/icon_seu.svg"))
        self.logo_seu.setObjectName("logo_seu")
        self.logo_seu.setStyleSheet("QLabel{\n"
"    border-left:20px;\n"
"}")
        self.verticalLayout.addWidget(self.logo_seu)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        self.stacked_widget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stacked_widget.sizePolicy().hasHeightForWidth())
        self.stacked_widget.setSizePolicy(sizePolicy)
        self.stacked_widget.setObjectName("stacked_widget")
        self.gridLayout.addWidget(self.stacked_widget, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stacked_widget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # 连接按钮组信号
        self.button_group.buttonClicked.connect(self.on_button_clicked)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "东南大学SARA射电望远镜"))
        self.btn_spectrum.setText(_translate("MainWindow", "谱线观测"))
        self.btn_record.setText(_translate("MainWindow", "频谱记录"))
        self.btn_direction.setText(_translate("MainWindow", "方向设置"))
        self.btn_calibration.setText(_translate("MainWindow", "系统校准"))
        self.btn_about.setText(_translate("MainWindow", "关于"))
        
    def on_button_clicked(self, button):
        """按钮点击事件处理"""
        button_id = self.button_group.id(button)
        # 根据按钮ID切换到对应的页面
        self.stacked_widget.setCurrentIndex(button_id)
        
    def add_external_ui(self, widget, index):
        """添加外部UI到stacked_widget中"""
        if index >= 0 and index < self.stacked_widget.count():
            # 如果该索引已有页面，先移除
            old_widget = self.stacked_widget.widget(index)
            if old_widget:
                self.stacked_widget.removeWidget(old_widget)
                old_widget.deleteLater()
        
        self.stacked_widget.insertWidget(index, widget)
        
    def set_external_ui(self, widgets_dict):
        """批量设置外部UI页面
        widgets_dict: {index: widget} 字典
        """
        for index, widget in widgets_dict.items():
            self.add_external_ui(widget, index)

# from . import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    
    # 示例：添加外部UI页面（这里用空QWidget代替）
    # 在实际使用中，你可以替换为你的实际UI页面
    try:
        from spectrum_page import Ui_spectrum_page
        from record_page import Ui_record_page
        
        spectrum_widget = QtWidgets.QWidget()
        ui_spectrum = Ui_spectrum_page()
        ui_spectrum.setupUi(spectrum_widget)
        
        record_page = QtWidgets.QWidget()
        ui_record = Ui_record_page()
        ui_record.setupUi(record_page)
        direction_page = QtWidgets.QWidget()
        calibration_page = QtWidgets.QWidget()
        about_page = QtWidgets.QWidget()
        
        # 设置页面到stacked_widget
        ui.add_external_ui(spectrum_widget, 0)
        ui.add_external_ui(record_page, 1)
        ui.add_external_ui(direction_page, 2)
        ui.add_external_ui(calibration_page, 3)
        ui.add_external_ui(about_page, 4)
        
        # 默认显示第一个页面
        ui.stacked_widget.setCurrentIndex(0)
        
        MainWindow.show()
        sys.exit(app.exec_())
    except ImportError as e:
        print(f"main_window.py导入错误: {e}")
        print("请确保所有依赖的UI文件都存在")