# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'record_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_record_page(object):
    def setupUi(self, record_page):
        record_page.setObjectName("record_page")
        record_page.resize(938, 567)
        self.verticalLayout = QtWidgets.QVBoxLayout(record_page)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_filepath = QtWidgets.QLineEdit(record_page)
        self.lineEdit_filepath.setReadOnly(True)
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.horizontalLayout.addWidget(self.lineEdit_filepath)
        self.button_browse = QtWidgets.QPushButton(record_page)
        self.button_browse.setObjectName("button_browse")
        self.horizontalLayout.addWidget(self.button_browse)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.button_recording = QtWidgets.QPushButton(record_page)
        self.button_recording.setCheckable(True)
        self.button_recording.setObjectName("button_recording")
        self.verticalLayout.addWidget(self.button_recording)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.frame_2 = QtWidgets.QFrame(record_page)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_14.addWidget(self.label_2)
        self.widget_integration = QtWidgets.QWidget(self.frame_2)
        self.widget_integration.setObjectName("widget_integration")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_integration)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_14.addWidget(self.widget_integration)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(4, 8)

        self.retranslateUi(record_page)
        QtCore.QMetaObject.connectSlotsByName(record_page)

    def retranslateUi(self, record_page):
        _translate = QtCore.QCoreApplication.translate
        record_page.setWindowTitle(_translate("record_page", "Form"))
        self.lineEdit_filepath.setText(_translate("record_page", "./"))
        self.button_browse.setText(_translate("record_page", "浏览.."))
        self.button_recording.setText(_translate("record_page", "开始"))
        self.label_2.setText(_translate("record_page", "<html><head/><body><p><span style=\" font-size:16pt;\">积分功率</span></p></body></html>"))
