# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'record_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_record_page(object):
    def setupUi(self, record_page):
        record_page.setObjectName("record_page")
        record_page.resize(938, 567)
        self.verticalLayout = QtWidgets.QVBoxLayout(record_page)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_filepath = QtWidgets.QLineEdit(record_page)
        self.lineEdit_filepath.setReadOnly(True)
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.horizontalLayout.addWidget(self.lineEdit_filepath)
        self.button_browse = QtWidgets.QPushButton(record_page)
        self.button_browse.setObjectName("button_browse")
        self.horizontalLayout.addWidget(self.button_browse)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(record_page)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_filename = QtWidgets.QLineEdit(record_page)
        self.lineEdit_filename.setInputMask("")
        self.lineEdit_filename.setMaxLength(32)
        self.lineEdit_filename.setFrame(True)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.horizontalLayout_3.addWidget(self.lineEdit_filename)
        self.button_recording = QtWidgets.QPushButton(record_page)
        self.button_recording.setCheckable(True)
        self.button_recording.setObjectName("button_recording")
        self.horizontalLayout_3.addWidget(self.button_recording)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.frame_2 = QtWidgets.QFrame(record_page)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.button_reflash = QtWidgets.QPushButton(self.frame_2)
        self.button_reflash.setObjectName("button_reflash")
        self.horizontalLayout_2.addWidget(self.button_reflash)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.list_record = QtWidgets.QListWidget(self.frame_2)
        self.list_record.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_record.setObjectName("list_record")
        self.verticalLayout_2.addWidget(self.list_record)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(record_page)
        self.button_reflash.clicked.connect(self.list_record.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(record_page)

    def retranslateUi(self, record_page):
        _translate = QtCore.QCoreApplication.translate
        record_page.setWindowTitle(_translate("record_page", "Form"))
        self.lineEdit_filepath.setText(_translate("record_page", "./"))
        self.button_browse.setText(_translate("record_page", "浏览.."))
        self.label.setText(_translate("record_page", "文件名："))
        self.lineEdit_filename.setText(_translate("record_page", "gr_record"))
        self.button_recording.setText(_translate("record_page", "开始"))
        self.label_2.setText(_translate("record_page", "<html><head/><body><p><span style=\" font-size:16pt;\">保存信息</span></p></body></html>"))
        self.button_reflash.setText(_translate("record_page", "刷新信息"))
